FROM tomcat:9-jre8-alpine

#install tools for dev
RUN apk add openjdk8
RUN apk add git
RUN apk add nmap
RUN apk add htop
RUN apk add vim

#install maven to /tools/maven
RUN wget http://apache.tt.co.kr/maven/maven-3/3.6.2/binaries/apache-maven-3.6.2-bin.tar.gz
RUN tar -xvzf apache-maven-3.6.2-bin.tar.gz && rm apache-maven-3.6.2-bin.tar.gz
RUN mkdir /tools
RUN mv ./apache-maven-3.6.2 /tools/apache-maven-3.6.2
RUN ln -s /tools/apache-maven-3.6.2 /tools/maven

RUN git clone https://github.com/herdin/SLT.git /tools/SLT
COPY application.properties /tools/SLT/src/main/resources/spring
WORKDIR /tools/SLT
RUN /tools/maven/bin/mvn package
RUN mv /tools/SLT/target/SLT.war /usr/local/tomcat/webapps

CMD ["catalina.sh", "run"]
