FROM tomcat:9-jre8

RUN apt-get update

#install maven to /tools/maven
RUN wget http://mirror.navercorp.com/apache/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.tar.gz
RUN tar -xvzf apache-maven-3.6.0-bin.tar.gz
RUN mkdir /tools
RUN mv ./apache-maven-3.6.0 /tools
RUN ln -s /tools/apache-maven-3.6.0 /tools/maven

#install tools for dev
RUN apt-get install -y openjdk-8-jdk
RUN apt-get install -y git
RUN apt-get install -y nmap
RUN apt-get install -y htop
RUN apt-get install -y vim
